name: Chrome Tests
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: install Google Chrome
        run: sudo apt-get install -y google-chrome-stable=106.0.5249.61

      - name: Install all dependencies
        run: npm install
      - name: Run tests
        run: npm run test:chrome:headless
      - name: Generate Reports
        if: always()
        run: npm run allure:generate
      - name: Upload Results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: allure-report
          path: ./docs/allure-report
      - name: Deploy to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-paged
          publish_dir: ./docs/allure-report
